### ISSUE TITLE
Remove gatsby-plugin-offline

### ISSUE THREAD

**Issue by jodymlin** [uclaacm/hack.uclaacm.com#119]
* Have been really annoyed lately by the "cache-first" behavior this plugin has
  * `gatsby-plugin-offline` defaults to a "cache-first" over a "network-first" behavior and as a result will always return a stale cached page first. The new page can be reloaded with a manual page refresh.
  * there is currently [no plan](https://github.com/gatsbyjs/gatsby/issues/11830) for the plugin to provide "network-first" behavior 
* This is rather inconvenient because we are constantly updating events and in order to get the most recent event list, the user must refresh the page. 
* Not sure how this will effect the speed/optimization of loading our page, but I am willing to experiment with this because this plug-in bugs me that much

* Another option is to specify that the pages that can be cached (this would not include the home/event page)

**Comment by TimothyGu** [comment]
Sad but okay
