### ISSUE TITLE
Fix Event Card Join Bug

### ISSUE THREAD

**Issue by jodymlin** [uclaacm/hack.uclaacm.com#121]
* Need to investigate why the JOIN button on the Event Card (during the period when it should be active), sometimes renders as `disabled`

Behavior witnessed (within a span of 15 minutes during the time when the button should have been enabled)
* JOIN button was active on Home Page, but not on Event Page
* JOIN button was active on Event Page, but not on Home Page
* After refreshing, but button would go from enabled to disabled (and vice versa)

**Comment by GalenWong** [comment]
Currently adopting a #122 no SSR solution. We need to investigate further on how Gatsby rehyrate on client-side to avoid future pitfalls.
