### ISSUE TITLE
Make timezone behavior consistent in dev mode and static build

### ISSUE THREAD

**Issue by GalenWong** [uclaacm/hack.uclaacm.com#123]
Right now, the dev mode is executed locally. `Date` object generated in `data/events.js` is created with local timezone. In netlify or github action build, timezone is always PT. We can change the `getDateTime` to always use PT.

**Comment by TimothyGu** [comment]
I think we should just set the timezone to Pacific on local builds too, which should be as easy as setting the `TZ=America/Los_Angeles` environment variable in `package.json`. If we care about supporting Windows, we could use [cross-env](https://www.npmjs.com/package/cross-env).
