### ISSUE TITLE
Update event highlights

### ISSUE THREAD

**Issue by jodymlin** [uclaacm/hack.uclaacm.com#135]
* update all event highlight banners, blurbs, and buttons

Note: the HOTH banner can be updated once the banner is ready from design

**Comment by jodymlin** [comment]
## Hack Sprint
*Banner*: new banner from design
*Blurb*: 
Hack Sprint is our beginner-friendly workshop series on mobile development with React Native. Through React Native, you'll be able to build apps for both Android and iOS devices at the same time!  You’ll also get to build and present your very own app in our final showcase. No previous mobile development experience is needed!
*Button:* Join the discord

## Hack Off the Hill 8
*Banner*: use old banner until design releases new one
*Blurb:* Hack off the Hill (HOTH 8) is the virtual edition of our annual hackathon. This 2-day long beginner-friendly hackathon is designed to give you a glimpse of a real hackathon. There will be workshops, mentors, and fun prizes for the best hacks! 
*Button:*: Application coming soon

## Hack Fam
Can leave everything as is

**Comment by khxia** [comment]
Is the signup form for Hackfam still the same link?

**Comment by jodymlin** [comment]
> Is the signup form for Hackfam still the same link?

Nope a different link. I just updated the blurb above 👍 Thanks for pointing that out

**Comment by khxia** [comment]
Any preference for ordering?

**Comment by jodymlin** [comment]
The preferred ordering of event highlights would be hack sprint, hack fam, then HOTH.
