### ISSUE TITLE
Change expand icon to minimize icon when archive accordion open

### ISSUE THREAD

**Issue by jodymlin** [uclaacm/hack.uclaacm.com#147]
When you expand a workshop series in the workshop archive, the + remains a +. Want the + to be a - when the accordion is open to indicate it will minimize the section.

**Comment by TimothyGu** [comment]
See sample code that does what we want: https://github.com/uclaacm/hoth.uclaacm.com/blob/e00a43ca1fecf9b567b38028b24104cf3573fd52/src/components/HomePage/FAQSection.js#L77-L104
