### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by GalenWong** [uclaacm/hack.uclaacm.com#203]

**Comment by GalenWong** [comment]
Notes:
- to reinstall `sharp`, run `rm -r node_modules/sharp` and `yarn install --check-files`

**Comment by GalenWong** [comment]
Fix webpack configuration. `Rule.isseur` changed. https://webpack.js.org/configuration/module/#ruleissuer

**Comment by GalenWong** [comment]
note: husky update

**Comment by khxia** [comment]
Installed two new packages:
- @emotion/react
- path-browserify -> this also had to be added to webpack as a fallback due to polyfill no longer being supported??
