### ISSUE TITLE
Clean up archive tags

### ISSUE THREAD

**Issue by jodymlin** [uclaacm/hack.uclaacm.com#205]
![image](https://user-images.githubusercontent.com/44387428/116839990-1e2bfa80-ab89-11eb-8369-9a5582e74e3c.png)

We have some tags like `machine learning` and `ml` that are redundant. We should also just go through and figure out some *proper* tags because there are tags like `todo list` which aren't that great :')

**Comment by TimothyGu** [comment]
My nominees:

* async storage
* await
* classes (could mean many things)
* components
* computer science
* explore
* express vs. expressjs (I vote for `express`)
* final project
* functional components
* functions (could mean many things)
* local storage
* machine learning vs. ml (I vote for `machine learning`)
* navigation (web? android? iOS?)
* props
* scripting
* state
* stylesheet vs. stylesheets (i vote for `stylesheets`)
* tech
* todo list
* ui (dup of design?)
* ux (dup of design?)
* views

On the other hand, I think there are also some tags we could add:

* react hooks

I also recommend that we add programmatic safeguards to make sure never to re-introduce the tags we deleted: i.e., a blocklist of tags.
