### ISSUE TITLE
Typo in Tim's OSS Passion Talk

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/hack.uclaacm.com#211]
Super minor typo, but I think this line 

https://github.com/uclaacm/hack.uclaacm.com/blob/main/src/data/events/archive/spring2020/passion-talks.yml#L17

which has YT link `https://www.youtube.com/watch?v=YrlG-mrUok` should instead have the link `https://www.youtube.com/watch?v=YrlG-mrUokY` instead (trailing `Y`)!

Wanted to show off Tim's passion talk 😞

**Comment by TimothyGu** [comment]
Would have been a perfect opportunity to demonstrate the use of a pull request :)

**Comment by TimothyGu** [comment]
Fixed in 5f310e36eca7ac3ffa8082eba241fd613118ee90. Also added slides link.
