### ISSUE TITLE
A comment section for each blog post?

### ISSUE THREAD

**Issue by GalenWong** [uclaacm/hack.uclaacm.com#23]
- checkout https://github.com/gitalk/gitalk
    - this is a hacky way of using github issues as a serverless comment system
- What about using AWS Lambda?

**Comment by khxia** [comment]
Could be worth checking out?
- [Facebook Comments Plugin](https://developers.facebook.com/docs/plugins/comments/ )

**Comment by GalenWong** [comment]
this is probably gonna be never implemented lol
