### ISSUE TITLE
Alpha-Test Internal Feedback

### ISSUE THREAD

**Issue by jodymlin** [uclaacm/hack.uclaacm.com#36]
This is the thread for hack members to provide feedback on the website :)

**Comment by GalenWong** [comment]
The shadow of the event cards on front page is cut off by an div (overflow: hidden). Can be fixed by adding some padding

**Comment by GalenWong** [comment]
We also want to implement image optimisation for the team page and the event page.

**Comment by TimothyGu** [comment]
I implemented image optimization on the team page. The homepage events section has been converted in #38, but I raised an open question on whether that's something we want to do.
