### ISSUE TITLE
Bug in archive page for safari

### ISSUE THREAD

**Issue by katelynsyu** [uclaacm/hack.uclaacm.com#380]
Looks like there’s a bug that makes the “Taught by” text render with the wrong styling in safari (iPhone, horizontal view)
![4AB3D195-DBD7-46EF-B926-421843708614](https://user-images.githubusercontent.com/41168140/224575656-411579db-ec91-4cb7-9853-09b6c5ec66e2.png)

**Comment by ariyin** [comment]
no problem anymore, could not reproduce error
