### ISSUE TITLE
Add /discord page

### ISSUE THREAD

**Issue by EinarBalan** [uclaacm/hack.uclaacm.com#383]
which just redirects to a permanent invite to the hack discord so that we don't have to tell people to go to discord.gg/lksdjflskdjflksdjfhlsdghslkdjflskdfjlksendmysufferingdjflkdfjlskdjfsldkjflskdfjsldkjfsdf

**Comment by jamesmwu** [comment]
Resolved by Lillian's PR, and will keep going forward into migration
