### ISSUE TITLE
update about page

### ISSUE THREAD

**Issue by katelynsyu** [uclaacm/hack.uclaacm.com#439]
- [ ] interns to officers (everyone ordered alphabetically by last name)
- [ ] change Jenna and Shiyu to co-pres and put their names first
- [ ] change Einar, Jakob, Katelyn, Maggie, James, Nathan to advisor, put their names last on the list, order them by last name alphabetically

**Comment by jamesmwu** [comment]
Fixed and merged by Max's PR
