### ISSUE TITLE
Images not showing for some blog posts

### ISSUE THREAD

**Issue by kristielim** [uclaacm/hack.uclaacm.com#77]
Seen on:
https://hack.uclaacm.com/posts/fall2018/hackschool-session-1/
https://hack.uclaacm.com/posts/fall2018/hackschool-session-3-backend/

<img width="660" alt="Screen Shot 2020-06-27 at 3 16 27 PM" src="https://user-images.githubusercontent.com/28357052/85933194-32c4a580-b889-11ea-9c9d-dcf0fe9ed1ac.png">

**Comment by TimothyGu** [comment]
It's working here, with Google Chrome on Linux. What browser/OS are you using?

**Comment by GalenWong** [comment]
works for me, @khxia and @jodymlin. @kristielim is there a way to reproduce it?

**Comment by kristielim** [comment]
Hm strange, when I checked again, the images loaded so I'm not sure what's going on.

**Comment by TimothyGu** [comment]
Sounds like some cache issue. In general, refreshing almost always works.
